from_latest_tag = false
ignore_merge_commits = true
tag_prefix = "v"
branch_whitelist = ["main"]
pre_bump_hooks = [
    "jq '.version=\"{{version}}\"' package.json | sponge package.json"
]
post_bump_hooks = [
    "git push",
    "git push origin v{{version}}"
]
pre_package_bump_hooks = []
post_package_bump_hooks = []

[commit_types]

[changelog]
path = "CHANGELOG.md"
remote = "github.com"
repository = "id-generator-webapp"
owner = "witcom-gmbh"
authors = [
    { signature = "Carsten Buchberger", username = "iceman91176" }
]

[bump_profiles]

[packages]